Add Reports Module and custom sql
bahmni-msf/gaza-config pull request #5
Opened 2022-11-30 06:03 UTC by shobanad16

2022-12-01 06:30 UTC, supriyatw requested changes

2022-12-01 06:30 UTC, supriyatw commented on openmrs/i18n/home/locale_en.json
> +    "MODULE_LABEL_EXPORTS_KEY": "fgjfgjfExports",
There's a typo here @shobanad16

2022-12-01 06:30 UTC, supriyatw commented on openmrs/apps/reports/extension.json
> +{}
why is this added?

2022-12-01 07:45 UTC, shobanad16 commented on openmrs/i18n/home/locale_en.json
> +    "MODULE_LABEL_EXPORTS_KEY": "fgjfgjfExports",
done

2022-12-01 07:45 UTC, shobanad16 commented on openmrs/apps/reports/extension.json
> +{}
not necessary. removed

2022-12-05 05:58 UTC, tarunkumar-tw commented on openmrs/apps/reports/extension.json
> +{}
@shobanad16 I still see the extension empty file. Please check if that empty file is needed or not and remove it

2022-12-05 06:07 UTC, shobanad16 commented on openmrs/apps/reports/extension.json
> +{}
@tarunkumar-tw yes this file is needed. if this file is deleted, then i get error when i click reports module.

2022-12-05 06:09 UTC, merged